### ISSUE TITLE
Use Number.NEGATIVE_INFINITY

### ISSUE THREAD

**Issue by lpatiny** [mljs/direct-optimization#10]
https://github.com/mljs/direct-optimization/blob/ab22e2850e24a1e6120357a7e73d0bfe5463a161/src/index.js#L212

**Comment by josoriom** [comment]
https://github.com/mljs/direct-optimization/blob/master/src/index.js#L208
https://github.com/mljs/direct-optimization/blob/master/src/index.js#L259
