### ISSUE TITLE
use ml-array-min and ml-array-max

### ISSUE THREAD

**Issue by lpatiny** [mljs/direct-optimization#12]
https://github.com/mljs/direct-optimization/blob/ab22e2850e24a1e6120357a7e73d0bfe5463a161/src/index.js#L275-L291

**Comment by josoriom** [comment]
https://github.com/mljs/direct-optimization/blob/master/src/index.js#L1
https://github.com/mljs/direct-optimization/blob/master/src/index.js#L2
